project_name: pomerium

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    main: ./cmd/pomerium/main.go
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: macos
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "README"
      - "readme"
      - "dependency"
      - "dep"
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

brews:
  - github:
      owner: pomerium
      name: homebrew-tap
    folder: Formula
    homepage: https://www.pomerium.io
    description: Authenticate, authorize, monitor, and secure user access to any application without a VPN.
    test: |
      system "#{bin}/pomerium --version"

dockers:
  - image_templates:
      - "pomerium/pomerium:{{ .Tag }}"
      - "pomerium/pomerium:latest"
    dockerfile: Dockerfile
    binaries:
      - pomerium
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=com.github.actions.name={{.ProjectName}}"
      - "--label=com.github.actions.description=Authenticate, authorize, monitor, and secure user access to any application without a VPN"
      - "--label=com.github.actions.icon=terminal"
      - "--label=com.github.actions.color=blue"
      - "--label=repository=http://github.com/pomerium/pomerium"
      - "--label=homepage=http://www.pomerium.io"
      - "--label=maintainer=Bobby DeSimone <bdd@pomerium.io>"
    extra_files:
      - go.mod
      - go.sum
    # goos: linux
    # goarch: amd64
    # goarm: ""
