name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #windows-latest :/
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/setup-go@master
        with:
          go-version: 1.13
      - uses: actions/checkout@master
      - run: make build
